#!/bin/sh
#
# Check that the code follows a consistant code style
# This script was shamelessly copied from GStreamer project as well as many other things
# File is called "jihn" in a name of the coding style that was developed one thoughsand
# years ago somewhere in Pacific Ocean.

# Check for existence of indent, and error out if not present.
# On some *bsd systems the binary seems to be called gnunindent,
# so check for that first.

version=`gnuindent --version 2>/dev/null`
if test "x$version" = "x"; then
  version=`indent --version 2>/dev/null`
  if test "x$version" = "x"; then
    echo "Bombolla git pre-commit hook:"
    echo "Did not find GNU indent, please install it before continuing."
    exit 1
  fi
  INDENT=indent
else
  INDENT=gnuindent
fi

case `$INDENT --version` in
  GNU*)
      ;;
  default)
      echo "Bombolla git pre-commit hook:"
      echo "Did not find GNU indent, please install it before continuing."
      echo "(Found $INDENT, but it doesn't seem to be GNU indent)"
      exit 1
      ;;
esac

INDENT_PARAMETERS="--line-length85 \
	--indent-level2 \
	--no-tabs \
	--tab-size8 \
        --struct-brace-indentation2 \
	--case-brace-indentation2 \
	--case-indentation0 \
        --indent-label0 \
	--continuation-indentation4 \
        --declaration-indentation2\
	--braces-on-if-line \
	--braces-on-struct-decl-line \
        --braces-on-func-def-line \
        --brace-indent2 \
        --no-space-after-casts \
        --cuddle-do-while \
	--cuddle-else \
        --blank-lines-after-declarations \
	--blank-lines-after-procedures \
        --blank-lines-after-commas \
        --break-before-boolean-operator \
        --spaces-around-initializers \
        --continue-at-parentheses \
        --paren-indentation2 \
        --preprocessor-indentation2 \
        --swallow-optional-blank-lines \
        --parameter-indentation2 \
	--honour-newlines"

if test "x$1" = "x"; then
    echo "--Checking style--"
    for file in `git diff-index --cached --name-only HEAD --diff-filter=ACMR| grep "\.[ch]$"` ; do
	# nf is the temporary checkout. This makes sure we check against the
	# revision in the index (and not the checked out version).
	nf=`git checkout-index --temp ${file} | cut -f 1`
	newfile=`mktemp /tmp/${nf}.XXXXXX` || exit 1
	$INDENT ${INDENT_PARAMETERS} \
		$nf -o $newfile 2>> /dev/null
	# FIXME: Call indent twice as it tends to do line-breaks
	# different for every second call.
	$INDENT ${INDENT_PARAMETERS} \
		$newfile 2>> /dev/null
	diff -u -p "${nf}" "${newfile}"
	r=$?
	rm "${newfile}"
	rm "${nf}"
	if [ $r != 0 ] ; then
	    echo "================================================================================================="
	    echo " Code style error in: $file                                                                      "
	    echo "                                                                                                 "
	    echo " Please fix before committing. Don't forget to run git add before trying to commit again.        "
	    echo " If the whole file is to be committed, this should work (run from the top-level directory):      "
	    echo "                                                                                                 "
	    echo "   jihn $file; git add $file; git commit"
	    echo "                                                                                                 "
	    echo "================================================================================================="
            exit 1
	fi
    done
    echo "--Checking style pass--"
else
    $INDENT ${INDENT_PARAMETERS} $@
fi
