public class ValaTest : GLib.Object {

    public virtual signal void say_hello() {
       stdout.printf("Hello! Vala is probably the best solution for Bombolla!\n");
    }
}

/* FIXME: To export this class as bombolla plugin, we need
 * to define a simple function:
 *
 * GType bombolla_plugin_system_get_gtype (void) {
 *   return vala_test_get_type ();
 * }
 *
 * C code generated by valac has vala_test_get_type () function and
 * TYPE_VALA_TEST macro, but we don't know how to use them from vala code.
 * It could be something like
 *
 * public GLib.Type bombolla_plugin_system_get_gtype () {
 *   return vala_test_get_type ();
 * }
 *
 * .. but valac doesn't accept it..
 * So, for now what we do is to compile it together with a small C file
 * register_plugin.c
 */
