name: Ubuntu build
on:
  push:
    branches: [ maestro ]
  pull_request:
    branches: [ maestro ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: bootstrap
      run: |
        sudo apt-get update -qq
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq libglib2.0-dev libsoup2.4-dev libpango1.0-dev libgjs-dev libpython3-dev automake pkg-config
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: configure
      run: ./autogen.sh
    - name: build
      run: make install
    - name: vaildate
      run: ./jihn --go-ahead
