name: Ubuntu build
on:
  push:
    branches: [ maestro ]
  pull_request:
    branches: [ maestro ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: bootstrap
      run: |
        sudo apt-get update -qq
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq libglib2.0-dev libsoup2.4-dev libgjs-dev libpython3-dev pkg-config indent valac ninja-build libcogl-pango-dev python3-pip python3-setuptools python3-wheel
        sudo pip install meson
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: validate
      run: ./jihn --full-check
