name: Ubuntu build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: bootstrap
      run: |
        sudo apt-get update -qq
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq libglib2.0-dev libsoup2.4-dev libgjs-dev libpython3-dev pkg-config indent valac ninja-build libcogl-pango-dev python3-pip python3-setuptools python3-wheel gtk-doc-tools
        sudo pip install meson
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: validate
      run: ./Firulais --ci-mode

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: artifacts
        path: build/firulais-examples-test-log.txt
        if-no-files-found: error
        retention-days: 90
